# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NSObject+Rx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NSObject+Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  target 'NSObject+RxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NSObject+RxUITests' do
    # Pods for testing
  end

end
